export const url = {
  logInUrl: `/api/login`,
  verifyEmail: `/api/verifyEmail`,
  updatePassword: `/api/updatePassword`,
  addService: `/api/serviceMange/addService`,
  updateService: `/api/serviceMange/updateService/`,
  viewService: '/api/serviceMange/listOfService',
  deleteService: `/api/serviceMange/deleteService/`,
  addEvent: `/api/eventMange/addEvent`,
  listOfEvent: `/api/eventMange/listOfEvent`,
  editEvent: `/api/eventMange/editEvent/`,
  deleteEvent: `/api/eventMange/deleteEvent/`,
  countOfBookingStatus: `/api/dashboard/countOfBookingStatus`,
  listOfLatestBooking: `/api/dashboard/listOfLatestBooking`,
  graphOfUser: `/api/dashboard/graphOfUser`,
  changePassword: `/api/changePassword `,
  bookingReport: `/api/report/bookingReport`,
  eventReport: `/api/report/eventReport`,
};
